import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Headet";
import Head from "next/head"
import ThemeWrapper from "@/components/ThemeWraper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
      <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@400;700&display=swap" rel="stylesheet"/>
      </Head>
      <ThemeWrapper>
        <Header />
        {children}
      </ThemeWrapper>
    </html>
  );
}
