import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Headet";
import ThemeWrapper from "@/components/ThemeWraper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeWrapper>
        <Header />
        {children}
      </ThemeWrapper>
    </html>
  );
}
